### ISSUE TITLE
Provisional rating support

### ISSUE THREAD

**Issue by jalpp** [lichess-org/lila-gif#147]
Currently ratings are not shown with ? If they are provisional, would make sense to add those 

Thanks

**Comment by niklasf** [comment]
The way to implement this would be to pass it from lila: https://github.com/lichess-org/lila/blob/9032b1ce7557fe2f889321f0bf012686264e07a9/modules/game/src/main/GifExport.scala#L42

**Comment by Oziomajnr** [comment]
Can we use https://github.com/lichess-org/lila/blob/caf68325b0fd212f3a99e45372002b362d94ba45/modules/game/src/main/Namer.scala#L39C16-L39C16 for the rating string instead? Since it already handles this case. Would it break anything in Lila?
So instead of 
```
def playerTextUser(player: Player, user: Option[LightUser], withRating: Boolean = false): String =
    player.aiLevel.fold(
      user.fold(player.name | "Anon.") { u =>
        player.rating.ifTrue(withRating).fold(u.titleName) { r =>
          s"${u.titleName} ($r)"
        }
      }
    ) { level =>
      s"Stockfish level $level"
    }
```

we can have 
```
def playerTextUser(player: Player, user: Option[LightUser], withRating: Boolean = false): String =
    player.aiLevel.fold(
      user.fold(player.name | "Anon.") { u =>
        player.ifTrue(withRating).fold(u.titleName) { p =>
          s"${u.titleName} ($ratingString(p))"
        }
      }
    ) { level =>
      s"Stockfish level $level"
    }

```

Let me know if this is fine ten I can implement this in Lila

**Comment by niklasf** [comment]
I think that's worth submitting as a pull request to lila.

**Comment by niklasf** [comment]
Thanks!
